development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:a9e9064538261894f0d8744f879737da@scat.redistogo.com:9575/
  channel_prefix: monster_audience_production
